### ISSUE TITLE
 CRITICAL - Was not able to extract station's name

### ISSUE THREAD

**Issue by cptnkoiz** [vlcty/check_clever_tanken#2]
Since 24th or so all my Stations return

CRITICAL - Was not able to extract station's name

did something change on the api?

**Comment by vlcty** [comment]
The "API" is parsing raw HTML :-)
I can confirm it's broken at the moment. The website looks different so they probably changed layout. Should not be that dramatic to fix. I'll have a look at it this evening.

**Comment by vlcty** [comment]
Fixed. Pull in the new file and you should be fine again.
