### ISSUE TITLE
API

### ISSUE THREAD

**Issue by SIRprise** [vlcty/check_clever_tanken#4]
(feature request / improvement)

Ich versuche gerade etwas Ähnliches und habe dabei eine API entdeckt:
/api/station-details/graph/v2?id=

Der String versteckt sich im chart-update-skript /static/js/dygraph_shared.bea7ee338da9.js in der Funktion fetchDygraphData. Die API erwartet aber wohl einen bestimmten header.

Vielleicht hilft das ja, um historische Daten zu bekommen und Charts zu erstellen

**Comment by vlcty** [comment]
Sorry, nicht gesehen! Aber mittlerweile auch hinfällig.
